{% set name = "rbdl" %}
{% set version = "2.6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/rbdl-casadi/archive/{{ version }}.tar.gz
  sha256: 7cff1e05318a5bcbdd920d634af0b4f8e50220aae713fa8323af01c1f6ef65fb

build:
  number: 2
  skip: True  # [win and vc<14]
  rpaths:
    - lib/
    - lib/{{ name }}/

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]
    - make  # [unix]
  host:
    - eigen
  run:
    - eigen

test:
  commands:
    - test $PREFIX/lib/librbdl$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Lib\\rbdl*.lib exit 1  # [win]

about:
  home: https://bitbucket.org/rbdl/rbdl
  license: Zlib
  license_file: LICENSE
  license_family: OTHER
  summary: RBDL is a highly efficient C++ library that contains some essential rigid body dynamics algorithms.

extra:
  recipe-maintainers:
    - pariterre
