{% set name = "rbdl" %}
{% set version = "3.1.0" %}
{% set build_num = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pariterre/rbdl-orb/archive/v{{ version }}.tar.gz
  sha256: 11c0c6c0a563cdd582c82e1cc4c0820c311705a8c55e3a996b2ff067f819a1a7

build:
  number: {{ build_num }}
  rpaths:
    - lib/
    - lib/{{ name }}/
  run_exports:
    - {{ pin_subpackage('rbdl', max_pin='x.x') }}
    
requirements:
  build:
    - {{ compiler('cxx') }}
    - pkgconfig
    - cmake
    - ninja
    - eigen
    - casadi
  host:
    - eigen
    - casadi
    - pkgconfig
  run:
    - eigen
    - casadi

test:
  commands:
    - test $PREFIX/lib/librbdl$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Lib\\rbdl*.lib exit 1  # [win]

about:
  home: https://bitbucket.org/rbdl/rbdl
  license: Zlib
  license_file: LICENSE
  summary: RBDL is a highly efficient C++ library that contains some essential rigid body dynamics algorithms.

extra:
  recipe-maintainers:
    - pariterre
