{% set name = "rbdl" %}
{% set version = "2.6.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/rbdl-casadi/archive/{{ version }}.tar.gz
  sha256: bd1173bfaef2da13fe1d8716950a09eefdbe22ce9f9e9cef25bbc3fa5e9fefed

build:
  number: 0
  skip: true  # [win and vc<14]
  rpaths:
    - lib/
    - lib/{{ name }}/
  run_exports:
    - {{ pin_subpackage('rbdl', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - {{ backend }}
  run:
    - {{ backend }}

test:
  commands:
    - test $PREFIX/lib/librbdl$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Lib\\rbdl*.lib exit 1  # [win]

about:
  home: https://bitbucket.org/rbdl/rbdl
  license: Zlib
  license_file: LICENSE
  summary: RBDL is a highly efficient C++ library that contains some essential rigid body dynamics algorithms.

extra:
  recipe-maintainers:
    - pariterre
