travis:
  secure:
    BINSTAR_TOKEN: YGEPL39hBQbAIIxxao3wHeofiqOJFjJqI2GaezYfA48lC5WCx2ycIihMDtfQbbnhqiqjntYNlJ2159HZrqlpvIZ6K+linpAjblySW4UnnXCkGLjogNcrnQv1EaMO9ig7rtifvwLL+Wce12fCNZ+o+yWnxMjfKQAOW8JJo5kXFwZLv94S646icBLO856WJtXlkNS6hco9f1aHO+HlC1B6pwXnUnR++jM5v/iPfu6HEw7bE/WkEg1ixYgffy/5L4PVDy5PZLu30VmFeKAVua/UsGFUzF2y3HjkJ//cPEAb7M7dD6msDOfIds2iKlwwhGsk7GDaILt5hLpu0jU877TepMN//kxgca/dXRjJe4mej6nwGhQRFG4RqD+GVr4pTvtqypLRBGtjyscjjHfxz0k4tp7ROj68d+3s3rM2aGOv5Op6WASjYWpH/GCUWZRG1+fGZLj+Ld6ImdTVH8Ai3HCzp7eLA8wFWIUB965pJmLIFBKjG5ZC/SwbkJSk278UguK4XtVRwngbyUXhq0hn4Ykl3hnmxltIM3Ae/ftZ+fwQrvFGtmbyNYeJZDkrT18eMNyfTmbCzFUXPMqOhmM9zgKG8KE9vhDylfSsSiMfEyPZ/FC/N3Yj8051axVdFU/g2GYF9mnTZkoTtScMSkpWO1CYit+5iPRV1/a1vo4kZNUQR9E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
